/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#000a76',
        'primary-container': '#111fa2',
        'on-primary': '#ffffff',
        'on-primary-container': '#8c96ff',
        'primary-fixed': '#dfe0ff',
        'primary-fixed-dim': '#bdc2ff',
        'on-primary-fixed': '#000767',
        'on-primary-fixed-variant': '#2935b2',
        'secondary': '#1550d3',
        'secondary-container': '#3c6bed',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#dce1ff',
        'secondary-fixed-dim': '#b5c4ff',
        'on-secondary-fixed': '#00164d',
        'on-secondary-fixed-variant': '#003cad',
        'tertiary': '#002623',
        'tertiary-container': '#003e3a',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#00b3a7',
        'tertiary-fixed': '#69f8eb',
        'tertiary-fixed-dim': '#45dbcf',
        'on-tertiary-fixed': '#00201d',
        'on-tertiary-fixed-variant': '#00504a',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#fbf8ff',
        'surface-dim': '#dbd9e3',
        'surface-bright': '#fbf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2fd',
        'surface-container': '#efecf7',
        'surface-container-high': '#e9e7f2',
        'surface-container-highest': '#e3e1ec',
        'surface-variant': '#e3e1ec',
        'surface-tint': '#4350ca',
        'on-surface': '#1b1b22',
        'on-surface-variant': '#454654',
        'on-background': '#1b1b22',
        'background': '#fbf8ff',
        'outline': '#767685',
        'outline-variant': '#c6c5d6',
        'inverse-surface': '#303038',
        'inverse-on-surface': '#f2effa',
        'inverse-primary': '#bdc2ff',
        'cta-amber': '#FFB547',
        'royal-blue': '#111FA2',
        'warm-amber': '#FFB547',
        'chip-bg': '#E6EAF2',
      },
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'h1': ['clamp(1.875rem, 6vw, 3rem)', { lineHeight: '1.15', letterSpacing: '0', fontWeight: '700' }],
        'h2': ['clamp(1.5rem, 4.5vw, 2.25rem)', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '700' }],
        'h3': ['clamp(1.25rem, 3vw, 1.5rem)', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'container-max': '1280px',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      maxWidth: {
        'container': '1280px',
      },
      boxShadow: {
        'card': '0px 4px 20px rgba(31, 41, 55, 0.05)',
        'card-hover': '0px 10px 30px rgba(31, 41, 55, 0.1)',
        'nav': '0px 4px 20px rgba(31, 41, 55, 0.05)',
        'mobile-nav': '0px -4px 20px rgba(31, 41, 55, 0.1)',
      }
    },
  },
  plugins: [],
}
